// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBih3RbY_pB0yNyrpFo2jEfIRZ4PaCDZlM',
    appId: '1:179427016165:web:702691979002f6d284830c',
    messagingSenderId: '179427016165',
    projectId: 'contacts-app-9cdb4',
    authDomain: 'contacts-app-9cdb4.firebaseapp.com',
    storageBucket: 'contacts-app-9cdb4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1vzKuGodtx2vB9cKY3UidxGSsd0engf0',
    appId: '1:179427016165:android:f4ca0fee992b45fd84830c',
    messagingSenderId: '179427016165',
    projectId: 'contacts-app-9cdb4',
    storageBucket: 'contacts-app-9cdb4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQU5lIQ26Dm6dQrQBKIsZLzFpltrCHz7g',
    appId: '1:179427016165:ios:f91b0418a52ca66484830c',
    messagingSenderId: '179427016165',
    projectId: 'contacts-app-9cdb4',
    storageBucket: 'contacts-app-9cdb4.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQU5lIQ26Dm6dQrQBKIsZLzFpltrCHz7g',
    appId: '1:179427016165:ios:f91b0418a52ca66484830c',
    messagingSenderId: '179427016165',
    projectId: 'contacts-app-9cdb4',
    storageBucket: 'contacts-app-9cdb4.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBih3RbY_pB0yNyrpFo2jEfIRZ4PaCDZlM',
    appId: '1:179427016165:web:471aa2be76e4392784830c',
    messagingSenderId: '179427016165',
    projectId: 'contacts-app-9cdb4',
    authDomain: 'contacts-app-9cdb4.firebaseapp.com',
    storageBucket: 'contacts-app-9cdb4.firebasestorage.app',
  );
}
